### ISSUE TITLE
Querying from different domain?

### ISSUE THREAD

**Issue by secmohammed** [amehat/nestjs-cqrs-saga#12]
Following the CQRS pattern, how would you query the categories at your example from products, since they're different domains?

**Comment by amehat** [comment]
My example is essentially a caricature. A domain is linked above all to the domain of business. You can query products with category constraints. However it depends on who makes this interrogation and that is what will really define the domain. For example a product to be interrogated by marketing will be a domain, but a product to be interrogated by a customer will be another domain.

**Comment by secmohammed** [comment]
It would be simple to just import the query at the domain even though it is at a different domain and just execute it, but I was just asking if its possible to query it from another domain without actually importing something from that different domain, to keep the domains decoupled as possible. I think you could achieve that through a third party like redis or whatever, but no matter what you do, you will have to import from the other domain which I was trying to figure out how to make bounded contexts communicate, but decoupled. If you have thoughts that could help with that, I would be grateful to hear back from you.

**Comment by amehat** [comment]
The domains must remain separate, it is the principle of boundaries, nevertheless you can indeed use an event store to which the domains can subscribe and process the data according to their context.
